modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile = "${mod_id}.png"
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_dependency_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${mod_id}.mixins.json"

